package ${entity.javaPackage};

import com.csi.jf.pay.common.dao.IDAO;

/**
 * This code is generated by FreeMarker
 * @author Administrator
 *
 */
public class ${entity.className}DAO extends IDAO {
   
}
